
-- Tabelas temporarias 

CREATE TABLE #MATRICULA 
    (
     NUM_MATRICULA INTEGER NOT NULL , 
     DAT_MATRICULA DATETIME NOT NULL , 
     VAL_MATRICULA DECIMAL (12,2) NOT NULL , 
     COD_ALUNO INTEGER NOT NULL, 
     CONSTRAINT MATRICULA_PK PRIMARY KEY CLUSTERED (NUM_MATRICULA)
    )
	
CREATE TABLE ##MATRICULA 
    (
     NUM_MATRICULA INTEGER NOT NULL , 
     DAT_MATRICULA DATETIME NOT NULL , 
     VAL_MATRICULA DECIMAL (12,2) NOT NULL , 
     COD_ALUNO INTEGER NOT NULL, 
     CONSTRAINT MATRICULA_PK_g PRIMARY KEY CLUSTERED (NUM_MATRICULA)
    )

SELECT	C.NOME, P.DATA_EMISSAO , P.ID_PEDIDO , P.VLR_TOTAL
FROM	TB_PEDIDO AS P
JOIN	TB_CLIENTE AS C ON C.ID_CLIENTE = P.ID_CLIENTE

--Utilizando a cláusula INTO
SELECT	C.NOME, P.DATA_EMISSAO , P.ID_PEDIDO , P.VLR_TOTAL
INTO #Pedidos_CLIENTE
FROM	TB_PEDIDO AS P
JOIN	TB_CLIENTE AS C ON C.ID_CLIENTE = P.ID_CLIENTE

SELECT * FROM #Pedidos_CLIENTE

SELECT C.NOME, P.ID_PEDIDO , P.DATA_EMISSAO, P.VLR_TOTAL
FROM TB_PEDIDO AS P
JOIN 
(SELECT MAX(ID_PEDIDO) AS ULT_PEDIDO, ID_CLIENTE
FROM TB_PEDIDO 
WHERE YEAR(DATA_EMISSAO)= 2017
GROUP BY ID_CLIENTE) AS PP ON P.ID_PEDIDO = PP.ULT_PEDIDO
JOIN TB_CLIENTE AS C ON C.ID_CLIENTE = P.ID_CLIENTE

--Criação de tabela temporária
SELECT MAX(ID_PEDIDO) AS ULT_PEDIDO, ID_CLIENTE
INTO #PEDIDO
FROM TB_PEDIDO 
WHERE YEAR(DATA_EMISSAO)= 2017
GROUP BY ID_CLIENTE

--Consulta realizando JOIN com a tabela temporária.
SELECT C.NOME, P.ID_PEDIDO , P.DATA_EMISSAO, P.VLR_TOTAL
FROM TB_PEDIDO AS P
JOIN #PEDIDO AS PP ON P.ID_PEDIDO = PP.ULT_PEDIDO
JOIN TB_CLIENTE AS C ON C.ID_CLIENTE = P.ID_CLIENTE

